# PULL BASE IMAGE
FROM jenkins/agent:alpine-jdk17

# SWITCH TO ROOT SINCE jenkins USER MIGHT/DOES NOT HAVE ENOUGH PERMISSION
USER root

# INSTALL PYTHON3 ON ALPINE LINUX USING ALPINE PACKAGE MANAGER -- apk
RUN apk add --no-cache python3 py3-pip py3-virtualenv

# SWITCH USER BACK TO JENKINS
USER jenkins